# Hight Performance Pandas and eval and query

In [1]:
import numpy as np 
rng = np.random.RandomState(42)
x = rng.random(1000000)
y = rng.random(1000000)
%timeit x+y

8.07 ms ± 770 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [2]:
#so doing this with the python is waste as it takes a lot time than this one

In [3]:
#usinng simple maskging in this is also waste because it do breakdown and run the things seprately then it come to the operation it can 
#cause the memory overalload for that high perfoormative tool are used called evall and query

In [4]:
#lets do the computation using the eval 
import pandas as pd 
nrows , ncoloumns = 1000000,100
df1,df2,df3,df4 = (pd.DataFrame(rng.random((nrows,ncoloumns))) for i in range (4))
#doing simple numpy style computation 
%timeit df1+df2+df3+df4

1.28 s ± 67.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [23]:
#doing the same computation using the eval of the pandas 

%timeit pd.eval('df1  + df2 + df3 + df4')

2.51 ms ± 109 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [24]:
#pd.eval performed the funcction 2x faster that is the big thing when you work with the billions of the rows

In [25]:
#operation from the eval

In [26]:
#integers 
df1, df2, df3, df4, df5 = (pd.DataFrame(rng.randint(0,1000,(100,3))) for i in range (5))

In [27]:
#doing the arithmatic operators 
result_1 = -df1*df2/(df1*df2)
result_2 = df1 + df2 + df3 + df4/(df1 + df2+ df3+ df4)

In [28]:
np.allclose(result_1,result_2)#since they are not equal on the terms

False

In [29]:
#comparison operators 
result_1 = (df1<df2) & (df2<=df3) & (df3!=df4)
result_2 = pd.eval('df1<df2 <= df3 != df4')

In [30]:
np.allclose(result_1,result_2)

True

In [31]:
#bitwise operators & and |
result_3 = (df1 < 0.5) & (df2 < 0.5) | (df3 < df4)

result_4 = ('(df1 < 0.5) & (df2 < 0.5) | (df3 < df4)')

In [34]:
%xmode Verbose
#np.allclose(result_3 , result_4)

Exception reporting mode: Verbose

In [35]:
#pd.eval can also support the index wise operation as well

In [36]:
#Dataframe.eval for the column wise operators

In [38]:
df = pd.DataFrame(rng.random((3000,3)) , columns = ['A' , 'B' , 'C'])

In [39]:
df.head()

          A         B         C
0  0.538350  0.156122  0.655632
1  0.741401  0.341425  0.929437
2  0.025977  0.790100  0.017946
3  0.111635  0.777786  0.926673
4  0.551732  0.449882  0.938579

In [40]:
df.describe()

                 A            B            C
count  3000.000000  3000.000000  3000.000000
mean      0.500148     0.499181     0.488236
std       0.286798     0.290174     0.293118
min       0.000097     0.000669     0.000244
25%       0.253723     0.252389     0.230679
50%       0.501056     0.498489     0.479463
75%       0.753365     0.755042     0.741474
max       0.999972     0.999983     0.999893

In [47]:
result1 = (df['A']+df['B'])/(df['C'] - 1)
result2 = pd.eval('(df.A + df.B) / (df.C - 1)')

In [48]:
np.allclose(result1,result2)

True

In [56]:
#checking new way to writing the column using the eval from the book
result3  = df.eval('(A+B)/(C-1)')

In [57]:
np.allclose(result2,result3)

True

In [58]:
np.allclose(result1,result3)

True

In [59]:
#so there are total three method an column wise operation can be performed

In [ ]:
#modified ways of doing the things in the pd.eval