In [1]:
#data aggregation on multiple indices

In [2]:
import pandas as pd 
import numpy as np

In [3]:
#creating heirarchical index for the index and columns 
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],
                                  names= ['year','visit']
                                )
columns = pd.MultiIndex.from_product([['Bob','Suzy','Michael'],['HR','Temp']],
                                    names = ['Name','Type'])

#making a fake data 
data = np.round(np.random.randn(4,6),1)#here we are making an array of 4,6 size and rounding that to 1 digit
data[:,::2] *= 10
data += 37

#creating the data frame 
health_data = pd.DataFrame(data,index = index , columns = columns)

In [4]:
health_data

Name         Bob        Suzy       Michael
Type          HR  Temp    HR  Temp      HR  Temp
year visit
2013 1      38.0  37.3  31.0  38.2    30.0  36.9
     2      42.0  36.7  46.0  37.3    46.0  36.6
2014 1      47.0  37.1  47.0  36.9    39.0  36.9
     2      38.0  37.3  24.0  35.6    46.0  36.3

In [5]:
#concating and appending the data sets

In [6]:
import pandas as pd 
import numpy as np

In [23]:
#function for making concated data frames 
def make_df(cols,ind):
    "Makes a quick Data frames"
    data = {c:[str(c)+str(i) for i in ind] for c in cols}
    return pd.DataFrame(data,ind)

In [24]:
make_df('ABC',range(3))

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [9]:
#making a class that will allow use to use multiple data frames side by side 
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}{1}
    """
    def __init__(self,*args):#storing all the arguments means variable etc 
        self.args = args

    def _repr_html_(self):
        return '\n'.join(self.template.format(a,eval(a)._repr_html_()) for a in self.args)

    def _repr_(self):
        return '\n\n'.join(a+'\n'+repr(eval(a)) for a in self.args)

In [10]:
#concatentaing in the numpy 
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]

In [12]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#for the 3 dimensional array 
x = [[1,2],
     [4,5]]

In [18]:
np.concatenate([x,x],axis = 1)

array([[1, 2, 1, 2],
       [4, 5, 4, 5]])

In [19]:
#concatenating in the pandas 
ser1 = pd.Series(['A','B','C'],index = [1,2,3])
ser2 = pd.Series(['D','F','E'],index = [1,2,3])

In [20]:
ser1

1    A
2    B
3    C
dtype: object

In [21]:
ser2

1    D
2    F
3    E
dtype: object

In [22]:
#concatenating the 2 series like numpy 
pd.concat([ser1,ser2])

1    A
2    B
3    C
1    D
2    F
3    E
dtype: object

In [25]:
df1 = make_df('AB',[1,2])
df2 = make_df('AB',[3,4])

In [26]:
df1

    A   B
1  A1  B1
2  A2  B2

In [27]:
df2

    A   B
3  A3  B3
4  A4  B4

In [30]:
df3 = pd.concat([df1,df2],axis = 0)

In [31]:
#using the our display jupyter function for displaying multiple table at the same time 
display('df1','df2','df3')

In [33]:
#duplicate indices 
#at the point pandas indices preserve even if we will make indices equal they will do the same task as it was supposed to be when it was
#with normal indexing it was doing before

In [35]:
#for example 
a = make_df('AB',  [1,2])
b = make_df('AB',  [3,4])

In [36]:
#so now we are matching the indices 
a.index  = b.index

In [38]:
pd.concat([a,b])

    A   B
3  A1  B1
4  A2  B2
3  A3  B3
4  A4  B4

In [39]:
#we have proved that thing in this function

In [40]:
#but now we have a problem that indices are repeated lets fix that thing

In [41]:
#treatng the repeated indices as the error

In [42]:
try:
    pd.concat([a,b],verify_integrity=True)
except ValueError as e:
    print(e)

Indexes have overlapping values: Index([3, 4], dtype='int64')

In [46]:
#ignorning the index 
pd.concat([a,b] ,  ignore_index=True)#this will ignore the index of the repeatinng index and will provide with the conisistent data

    A   B
0  A1  B1
1  A2  B2
2  A3  B3
3  A4  B4