# Aggregation and grouping

A fundamental piece of many data analysis tasks is efficient summarization: computing
aggregations like sum, mean, median, min, and max, in which a single number summarizes
aspects of a potentially large dataset. In this chapter, we’ll explore
aggregations in Pandas, from simple operations akin to what we’ve seen on NumPy
arrays to more sophisticated operations based on the concept of a groupby.

In [1]:
import numpy as np 
import pandas as pd 
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}{1}
    """
    def __init__(self, *args):
        self.args = args
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
        for a in self.args)
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
        for a in self.args)

In [2]:
#so now  we will download the planets data via seaborn package

In [3]:
import seaborn as sns 
planets = sns.load_dataset('planets')
planets

               method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [4]:
#simple aggregation in the pandas 
#these are aggregation which are more like numpy aggregation

In [5]:
rng = np.random.RandomState(42)
data = pd.Series(rng.rand(5))

In [6]:
data

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [7]:
data.sum()

np.float64(2.811925491708157)

In [8]:
#basic aggregation 
data.mean()

np.float64(0.5623850983416314)

In [9]:
DataFrame = pd.DataFrame({'A': rng.rand(5),
                         'B': rng.rand(5)})

In [10]:
DataFrame

          A         B
0  0.155995  0.020584
1  0.058084  0.969910
2  0.866176  0.832443
3  0.601115  0.212339
4  0.708073  0.181825

In [11]:
#now performing the simple ones for the Dataframes it 
DataFrame.sum()

A    2.389442
B    2.217101
dtype: float64

In [12]:
DataFrame.mean()

A    0.477888
B    0.443420
dtype: float64

In [13]:
DataFrame.std()

A    0.353125
B    0.426952
dtype: float64

In [14]:
DataFrame.mean(axis ='columns')

0    0.088290
1    0.513997
2    0.849309
3    0.406727
4    0.444949
dtype: float64

In [15]:
planets.isnull().any()

method            False
number            False
orbital_period     True
mass               True
distance           True
year              False
dtype: bool

In [16]:
#cleaning the data by dropping the null values 
planets.dropna().isnull().any()

method            False
number            False
orbital_period    False
mass              False
distance          False
year              False
dtype: bool

In [17]:
planets.describe()

            number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [18]:
planets.min()

method            Astrometry
number                     1
orbital_period      0.090706
mass                  0.0036
distance                1.35
year                    1989
dtype: object

### groupby : split , apply , combine

In [19]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
'data': range(6)},columns = ['key','data'])

In [20]:
df.groupby('key').sum()#summinng the key values which are common

     data
key
A       3
B       5
C       7

In [21]:
df.groupby('key').mean()

     data
key
A     1.5
B     2.5
C     3.5

In [22]:
df.groupby('key')

In [23]:
#groupby funciton is special it is not viewd as Dataframe but as the DataFrameGroupBy

In [24]:
#groupby object

In [25]:
#basic group by function 
planets.groupby('method'),planets.groupby('method')['orbital_period']

(<pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000018AAA9936F0>,
 <pandas.core.groupby.generic.SeriesGroupBy object at 0x0000018AAA9EABA0>)

In [26]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [27]:
planets.groupby('method').median()

                               number  orbital_period   mass  distance    year
method
Astrometry                        1.0      631.180000    NaN    17.875  2011.5
Eclipse Timing Variations         2.0     4343.500000  5.125   315.360  2010.0
Imaging                           1.0    27500.000000    NaN    40.395  2009.0
Microlensing                      1.0     3300.000000    NaN  3840.000  2010.0
Orbital Brightness Modulation     2.0        0.342887    NaN  1180.000  2011.0
Pulsar Timing                     3.0       66.541900    NaN  1200.000  1994.0
Pulsation Timing Variations       1.0     1170.000000    NaN       NaN  2007.0
Radial Velocity                   1.0      360.200000  1.260    40.445  2009.0
Transit                           1.0        5.714932  1.470   341.000  2012.0
Transit Timing Variations         2.0       57.011000    NaN   855.000  2012.5

In [28]:
#group by functioin direct iteration over the groups we can apply thing on that 
#code 
for (method , group) in  planets.groupby('method') :
    
    print("{0:30s} shape = {1}".format(method,group.shape))

Astrometry                     shape = (2, 6)
Eclipse Timing Variations      shape = (9, 6)
Imaging                        shape = (38, 6)
Microlensing                   shape = (23, 6)
Orbital Brightness Modulation  shape = (3, 6)
Pulsar Timing                  shape = (5, 6)
Pulsation Timing Variations    shape = (1, 6)
Radial Velocity                shape = (553, 6)
Transit                        shape = (397, 6)
Transit Timing Variations      shape = (4, 6)

In [29]:
#dispatch method - basically means that we can apply some of data frame objects fucnotin on the grouped object 
#means where we applied groupby

In [30]:
planets.groupby('method')['year'].describe().unstack()

       method
count  Astrometry                          2.0
       Eclipse Timing Variations           9.0
       Imaging                            38.0
       Microlensing                       23.0
       Orbital Brightness Modulation       3.0
                                         ...
max    Pulsar Timing                    2011.0
       Pulsation Timing Variations      2007.0
       Radial Velocity                  2014.0
       Transit                          2014.0
       Transit Timing Variations        2014.0
Length: 80, dtype: float64

In [31]:
#aggregate , filter ,  transform and apply in the group by other than basic numpy operatoin and iteration , dispachig etc

In [34]:
rng = np.random.RandomState(42)
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'data1':range(6),
                   'data2': rng.randint(0,6,6)},
                   columns = ['key','data1','data2'])

In [35]:
df

  key  data1  data2
0   A      0      3
1   B      1      4
2   C      2      2
3   A      3      4
4   B      4      4
5   C      5      1

In [36]:
#aggregate

In [43]:
df.groupby('key').aggregate(['min',np.median,'max'])

C:\Users\Monu Verma\AppData\Local\Temp\ipykernel_19560\2511337658.py:1: FutureWarning: The provided callable <function median at 0x0000018AA4DF1C60> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  df.groupby('key').aggregate(['min',np.median,'max'])

    data1            data2
      min median max   min median max
key
A       0    1.5   3     3    3.5   4
B       1    2.5   4     4    4.0   4
C       2    3.5   5     1    1.5   2

In [44]:
df.groupby('key').aggregate({'data1':'min',
                            'data2':'max'})

     data1  data2
key
A        0      4
B        1      4
C        2      2

In [52]:
#using filter in the pandas 
def filter_func (x):
    "filter func where std should be more than 4"
    return x['data2'].std()>3


display('df',' df.groupby("key").std()',' df.groupby("key").filter(filter_func)')

df
  key  data1  data2
0   A      0      3
1   B      1      4
2   C      2      2
3   A      3      4
4   B      4      4
5   C      5      1

 df.groupby("key").std()
       data1     data2
key
A    2.12132  0.707107
B    2.12132  0.000000
C    2.12132  0.707107

 df.groupby("key").filter(filter_func)
Empty DataFrame
Columns: [key, data1, data2]
Index: []

In [ ]:
#transform method in the pandas