### Chapter - Concatenation and appends

In [1]:
import pandas as pd 
import numpy as np

In [2]:
#creating heirarchical index for the index and columns 
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],
                                  names= ['year','visit']
                                )
columns = pd.MultiIndex.from_product([['Bob','Suzy','Michael'],['HR','Temp']],
                                    names = ['Name','Type'])

#making a fake data 
data = np.round(np.random.randn(4,6),1)#here we are making an array of 4,6 size and rounding that to 1 digit
data[:,::2] *= 10
data += 37

#creating the data frame 
health_data = pd.DataFrame(data,index = index , columns = columns)

In [3]:
health_data

Name         Bob        Suzy       Michael
Type          HR  Temp    HR  Temp      HR  Temp
year visit
2013 1      23.0  36.6  42.0  39.5    35.0  36.1
     2      26.0  38.4   9.0  37.4    35.0  37.2
2014 1      24.0  39.0  37.0  38.0    30.0  36.8
     2      46.0  36.5  34.0  36.0    39.0  35.2

In [4]:
#concating and appending the data sets

In [5]:
import pandas as pd 
import numpy as np

In [6]:
#function for making concated data frames 
def make_df(cols,ind):
    "Makes a quick Data frames"
    data = {c:[str(c)+str(i) for i in ind] for c in cols}
    return pd.DataFrame(data,ind)

In [7]:
make_df('ABC',range(3))

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [8]:
#making a class that will allow use to use multiple data frames side by side 
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}{1}
    """
    def __init__(self,*args):#storing all the arguments means variable etc 
        self.args = args

    def _repr_html_(self):
        return '\n'.join(self.template.format(a,eval(a)._repr_html_()) for a in self.args)

    def _repr_(self):
        return '\n\n'.join(a+'\n'+repr(eval(a)) for a in self.args)

In [9]:
#concatentaing in the numpy 
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]

In [10]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#for the 3 dimensional array 
x = [[1,2],
     [4,5]]

In [12]:
np.concatenate([x,x],axis = 1)

array([[1, 2, 1, 2],
       [4, 5, 4, 5]])

In [13]:
#concatenating in the pandas 
ser1 = pd.Series(['A','B','C'],index = [1,2,3])
ser2 = pd.Series(['D','F','E'],index = [1,2,3])

In [14]:
ser1

1    A
2    B
3    C
dtype: object

In [15]:
ser2

1    D
2    F
3    E
dtype: object

In [16]:
#concatenating the 2 series like numpy 
pd.concat([ser1,ser2])

1    A
2    B
3    C
1    D
2    F
3    E
dtype: object

In [17]:
df1 = make_df('AB',[1,2])
df2 = make_df('AB',[3,4])

In [18]:
df1

    A   B
1  A1  B1
2  A2  B2

In [19]:
df2

    A   B
3  A3  B3
4  A4  B4

In [20]:
df3 = pd.concat([df1,df2],axis = 0)

In [21]:
#using the our display jupyter function for displaying multiple table at the same time 
display('df1','df2','df3')

In [22]:
#duplicate indices 
#at the point pandas indices preserve even if we will make indices equal they will do the same task as it was supposed to be when it was
#with normal indexing it was doing before

In [23]:
#for example 
a = make_df('AB',  [1,2])
b = make_df('AB',  [3,4])

In [24]:
#so now we are matching the indices 
a.index  = b.index

In [25]:
pd.concat([a,b])

    A   B
3  A1  B1
4  A2  B2
3  A3  B3
4  A4  B4

In [26]:
#we have proved that thing in this function

In [27]:
#but now we have a problem that indices are repeated lets fix that thing

In [28]:
#treatng the repeated indices as the error

In [29]:
try:
    pd.concat([a,b],verify_integrity=True)
except ValueError as e:
    print(e)

Indexes have overlapping values: Index([3, 4], dtype='int64')

In [30]:
#ignorning the index 
pd.concat([a,b] ,  ignore_index=True)#this will ignore the index of the repeatinng index and will provide with the conisistent data

    A   B
0  A1  B1
1  A2  B2
2  A3  B3
3  A4  B4

In [31]:
#adding multi index while the concatentating the values

In [32]:
#for example doing adding x and y in our a and b concatenating data 
pd.concat([a,b],keys=['x','y'])#maked the keys x and y

      A   B
x 3  A1  B1
  4  A2  B2
y 3  A3  B3
  4  A4  B4

In [33]:
#concatenation with the joins

In [34]:
# the data sets which doesnot have same not of columns in the number 
df5 = make_df('ABC',[0,1])
df6 = make_df('BCD',[2,3])#so there is D and A uncommon in both of them in the respect to each other

In [35]:
display('df5','df6','pd.concat([df5,df6])')

In [36]:
#as we can see the values that are uncommon in the respect to each of the data is A and  D in respect to each other

In [37]:
#there are two methods either filling the na values or using join method inner lets use since we have not used it early

In [38]:
pd.concat([df5,df6],join='inner')#it basically removed the rows with the value with nan

    B   C
0  B0  C0
1  B1  C1
2  B2  C2
3  B3  C3

In [39]:
#append method in the pandas after the concatenation

In [40]:
df1

    A   B
1  A1  B1
2  A2  B2

In [44]:
df2

    A   B
3  A3  B3
4  A4  B4