# Pivot Tables :-

The pivot similar kind of operation like gropy it also take columns as input and perform oor summarise the data or perform function on the data based on the input we provided

The difference is that pivot is multidimensional version of the groupby function lets explore that type of tables

In [1]:
#lets see what it add in our inventory

In [3]:
import numpy as np 
import pandas as pd 
import seaborn as sns 


#loading the titanic data to perform the function on the data and learn the concept 
titanic = sns.load_dataset('titanic')#it is data of the titanic which is like data for about something 
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [4]:
#survival rate on  the basis of the sex 
titanic.groupby('sex')['survived'].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [9]:
#digging more in the data by finding the survival rate on the basis of the both class and the sex 
titanic.groupby(['class','sex'])['survived'].aggregate('mean').unstack()

C:\Users\Monu Verma\AppData\Local\Temp\ipykernel_2144\2828715795.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(['class','sex'])['survived'].aggregate('mean').unstack()

sex       female      male
class
First   0.968085  0.368852
Second  0.921053  0.157407
Third   0.500000  0.135447

In [10]:
#here we observed that first class survival rate of female is good only 1 is dying in 20 and in men it is 1 is surviving in 3 
#here the worst for both women and men becomes at the third class where women surving rate decrease to the 50 percent and for men it decirease 26 percent

In [12]:
#pivot table 
titanic.pivot_table('survived' , index = 'sex' , columns = 'class' , aggfunc = 'mean')

C:\Users\Monu Verma\AppData\Local\Temp\ipykernel_2144\3017234222.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table('survived' , index = 'sex' , columns = 'class' , aggfunc = 'mean')

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [13]:
#Multilevel pivot table

In [ ]:
age = pd.cut(titanic['age',])