# Vectorized operation in Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
#vectorization 
x = np.array([2,3,3,4,5,5,6,6])
x*2

array([ 4,  6,  6,  8, 10, 10, 12, 12])

In [3]:
#problem with  vectorizatoin it is very verbose means details about thing 
data = ['paul','maRy','Pink','Blue']
[s.capitalize() for s in data]

['Paul', 'Mary', 'Pink', 'Blue']

In [4]:
#by pandas it is very conveniencet and error prone free 
data = pd.Series(['paul','chinki','kai','tyson'])
data.str.capitalize()

0      Paul
1    Chinki
2       Kai
3     Tyson
dtype: object

In [5]:
#lets start today work 
#table of the pandas string method 
monte = pd.Series(['Graham Chapman', 'John Cleese', 'Terry Gilliam',
'Eric Idle', 'Terry Jones', 'Michael Palin'])

In [6]:
monte

0    Graham Chapman
1       John Cleese
2     Terry Gilliam
3         Eric Idle
4       Terry Jones
5     Michael Palin
dtype: object

In [7]:
#mthods of the pandas for doing the vectorization with the pandas 
monte.str.len()

0    14
1    11
2    13
3     9
4    11
5    13
dtype: int64

In [8]:
monte.str.lower()

0    graham chapman
1       john cleese
2     terry gilliam
3         eric idle
4       terry jones
5     michael palin
dtype: object

In [9]:
monte.str.capitalize()

0    Graham chapman
1       John cleese
2     Terry gilliam
3         Eric idle
4       Terry jones
5     Michael palin
dtype: object

In [10]:
monte.str.upper()#for captilzing every letter in the sentence

0    GRAHAM CHAPMAN
1       JOHN CLEESE
2     TERRY GILLIAM
3         ERIC IDLE
4       TERRY JONES
5     MICHAEL PALIN
dtype: object

monte.str.isdigit()

In [11]:
monte.str.isdigit()#for checking series have digit  or not

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [12]:
monte.str.split()#for splitting the different words in the seiries

0    [Graham, Chapman]
1       [John, Cleese]
2     [Terry, Gilliam]
3         [Eric, Idle]
4       [Terry, Jones]
5     [Michael, Palin]
dtype: object

In [13]:
monte.str.startswith('T')#for cheking if the values starts with desired character or not

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [14]:
monte.str.startswith('A')

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [15]:
#methods using the regular expresions

In [16]:
monte.str.extract('([A-Za-z]+)',expand=False)

0     Graham
1       John
2      Terry
3       Eric
4      Terry
5    Michael
dtype: object

In [17]:
monte.str.extract('([A-Za-z]+)',expand = False)

0     Graham
1       John
2      Terry
3       Eric
4      Terry
5    Michael
dtype: object

In [18]:
monte.str.findall(r'^[^AEIOU].*[^aeiou]$')#so here basically we are saying that find the values which are not starting and ending with the vowel so we will just get the words that are starting with the consonants

0    [Graham Chapman]
1                  []
2     [Terry Gilliam]
3                  []
4       [Terry Jones]
5     [Michael Palin]
dtype: object

In [19]:
#Miscellenous methods in between the pandas and pythonn strings

Other methods then basic pandas vectorization methods and regular expression methods 
get Indexes each element
slice Slices each element
slice_replace Replaces slice in each element with the passed value
cat Concatenates strings
repeat Repeats values
normalize Returns Unicode form of strings
pad Adds whitespace to left, right, or both sides of strings
wrap Splits long strings into lines with length less than a given width
join Joins strings in each element of the Series with the passed separator
get_dummies Extracts dummy variables as a DataFrame

In [20]:
#normal indexing 
monte[0:3]

0    Graham Chapman
1       John Cleese
2     Terry Gilliam
dtype: object

In [21]:
#slicing of the str 
monte.str[0:3]

0    Gra
1    Joh
2    Ter
3    Eri
4    Ter
5    Mic
dtype: object

In [22]:
#splliting through the indexes using the slicing of the string 
monte.str.split().str[-1]

0    Chapman
1     Cleese
2    Gilliam
3       Idle
4      Jones
5      Palin
dtype: object

In [23]:
#indicator codes - codes such we specify something inn the data to make the data look clean and stable
#for example all the people with failing marks as F and students in these certain range or duplicats as a, b c etc

In [24]:
# #vectorizing the indicator codes 
# as A = “born in America,” B = “born in the United Kingdom,” C = “likes cheese,”
# D = “likes spam”:
full_monte = pd.DataFrame({'name':monte,
                          'info':['B|C|D','B|D','C|A','A|D','A|C|D','B|C']})

In [25]:
full_monte

             name   info
0  Graham Chapman  B|C|D
1     John Cleese    B|D
2   Terry Gilliam    C|A
3       Eric Idle    A|D
4     Terry Jones  A|C|D
5   Michael Palin    B|C

In [26]:
#getting dummies of the data 
full_monte['info'].str.get_dummies('|')

   A  B  C  D
0  0  1  1  1
1  0  1  0  1
2  1  0  1  0
3  1  0  0  1
4  1  0  1  1
5  0  1  1  0

In [27]:
#mini vector  project

Example - Recipe database

In [28]:
import pandas as pd 
import numpy as np

In [29]:
recipes = pd.read_json('recipeitems.json',lines=True)

In [30]:
recipes

,_id,name,ingredients,url,image,ts,cookTime,source,recipeYield,datePublished,prepTime,description,totalTime,creator,recipeCategory,dateModified,recipeInstructions
0,{'$oid': '5160756b96cc62079cc2db15'},Drop Biscuits and Sausage Gravy,Biscuits\n3 cups All-purpose Flour\n2 Tablespo...,http://thepioneerwoman.com/cooking/2013/03/dro...,http://static.thepioneerwoman.com/cooking/file...,{'$date': 1365276011104},PT30M,thepioneerwoman,12,2013-03-11,PT10M,"Late Saturday afternoon, after Marlboro Man ha...",NaN,NaN,NaN,NaN,NaN
1,{'$oid': '5160756d96cc62079cc2db16'},Hot Roast Beef Sandwiches,12 whole Dinner Rolls Or Small Sandwich Buns (...,http://thepioneerwoman.com/cooking/2013/03/hot...,http://static.thepioneerwoman.com/cooking/file...,{'$date': 1365276013902},PT20M,thepioneerwoman,12,2013-03-13,PT20M,"When I was growing up, I participated in my Ep...",NaN,NaN,NaN,NaN,NaN
2,{'$oid': '5160756f96cc6207a37ff777'},Morrocan Carrot and Chickpea Salad,Dressing:\n1 tablespoon cumin seeds\n1/3 cup /...,http://www.101cookbooks.com/archives/moroccan-...,http://www.101cookbooks.com/mt-static/images/f...,{'$date': 1365276015332},NaN,101cookbooks,NaN,2013-01-07,PT15M,A beauty of a carrot salad - tricked out with ...,NaN,NaN,NaN,NaN,NaN
3,{'$oid': '5160757096cc62079cc2db17'},Mixed Berry Shortcake,Biscuits\n3 cups All-purpose Flour\n2 Tablespo...,http://thepioneerwoman.com/cooking/2013/03/mix...,http://static.thepioneerwoman.com/cooking/file...,{'$date': 1365276016700},PT15M,thepioneerwoman,8,2013-03-18,PT15M,It's Monday! It's a brand new week! The birds ...,NaN,NaN,NaN,NaN,NaN
4,{'$oid': '5160757496cc6207a37ff778'},Pomegranate Yogurt Bowl,For each bowl: \na big dollop of Greek yogurt\...,http://www.101cookbooks.com/archives/pomegrana...,http://www.101cookbooks.com/mt-static/images/f...,{'$date': 1365276020318},NaN,101cookbooks,Serves 1.,2013-01-20,PT5M,A simple breakfast bowl made with Greek yogurt...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173273,{'$oid': '551c030e96cc6233c0d0dc3d'},The Easiest Homemade Vanilla Ice Cream,250 milliliters Cream\n395 grams Canned Sweete...,http://tastykitchen.com/recipes/desserts/the-e...,http://tastykitchen.com/recipes/wp-content/upl...,{'$date': 1427899150211},PT,tastykitchen,10,2015-04-01,PT10M,The easiest vanilla ice cream you will ever ma...,NaN,NaN,NaN,NaN,NaN
173274,{'$oid': '551c030f96cc6233c0d0dc3e'},Butterfinger Eggs with Vanilla,2 cups Candy Corn\n1 teaspoon Vanilla Extract\...,http://tastykitchen.com/recipes/holidays/butte...,http://tastykitchen.com/recipes/wp-content/upl...,{'$date': 1427899151232},PT5M,tastykitchen,24,2015-04-01,PT8H,Chocolate coated peanut butter eggs with a hin...,NaN,NaN,NaN,NaN,NaN
173275,{'$oid': '551c86b796cc626b1ab4d901'},The Best Homemade Taco Seasoning,1/4 cup ground cumin\n1/4 cup kosher salt\n2 t...,http://picky-palate.com/2015/04/01/the-best-ho...,http://picky-palate.com/wp-content/uploads/201...,{'$date': 1427932855918},NaN,pickypalate,Makes about 1 cup,2015-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173276,{'$oid': '551f29b696cc62227991d465'},The Ultimate Queso Bean Dip,Two 16 ounce cans Old El Paso Refried Beans\n4...,http://picky-palate.com/2015/04/03/the-ultimat...,http://picky-palate.com/wp-content/uploads/201...,{'$date': 1428105654508},NaN,pickypalate,8-10 Servings,2015-04-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN
173277,{'$oid': '551f29c696cc6222a4e0c0e4'},Maple-Sweetened Banana Muffins,⅓ cup melted coconut oil or extra-virgin olive...,http://cookieandkate.com/2015/healthy-banana-m...,http://cookieandkate.com/images/2015/04/mashed...,{'$date': 1428105670708},PT25M,cookieandkate,11 muffins,NaN,PT10M,"These whole wheat, maple-sweetened banana muff...",NaN,NaN,NaN,NaN,NaN

In [31]:
recipes.iloc[0]

_id                                {'$oid': '5160756b96cc62079cc2db15'}
name                                    Drop Biscuits and Sausage Gravy
ingredients           Biscuits\n3 cups All-purpose Flour\n2 Tablespo...
url                   http://thepioneerwoman.com/cooking/2013/03/dro...
image                 http://static.thepioneerwoman.com/cooking/file...
ts                                             {'$date': 1365276011104}
cookTime                                                          PT30M
source                                                  thepioneerwoman
recipeYield                                                          12
datePublished                                                2013-03-11
prepTime                                                          PT10M
description           Late Saturday afternoon, after Marlboro Man ha...
totalTime                                                           NaN
creator                                                             NaN
recipeCategory                                                      NaN
dateModified                                                        NaN
recipeInstructions                                                  NaN
Name: 0, dtype: object

In [32]:
#so my work is to make a list of the ingrdient of making a recipe 
recipes.ingredients.str.len().describe()#so here we are taking description of the recipes ingrdients lenght of the full data

count    173278.000000
mean        244.617926
std         146.705285
min           0.000000
25%         147.000000
50%         221.000000
75%         314.000000
max        9067.000000
Name: ingredients, dtype: float64

In [33]:
#so max chracters are 625 and average chracters is 226 and no of ingrdients of the recipes in the data is 1090

In [34]:
#let find which recipe have 625 character of ingridient 
recipes.name[np.argmax(recipes.ingredients.str.len().describe())]

'Drop Biscuits and Sausage Gravy'

In [35]:
#so the recipe with the highest number of ingredients is apple cranberry  crostada

In [36]:
#letss find the withe lowest character 
recipes.name[np.argmin(recipes.ingredients.str.len().describe())]

'Mixed Berry Shortcake'

In [37]:
#apple crisp is with lowest

In [38]:
#finding how many of them is including inn the the ingridients
recipes.ingredients.str.contains('[Cc]innamon').sum()

np.int64(10526)

In [39]:
#finding how many of them has misppeled as cinamon 
recipes.ingredients.str.contains('[Cc]inamon').sum()#so there isnt any

np.int64(11)

In [40]:
recipes.ingredients.str.contains('[Ss]alt').sum()

np.int64(63487)

In [41]:
#lets check how many  recipes take one hour to cook 
recipes.cookTime.str.contains('1').sum()#so there are 137 dishes which are taking exactly 1 hr to make

39824

## A recipe recommender

In [42]:
#basically given the ingridient the person have it will recommend a recipe according to data 
spice_list = ['salt', 'pepper', 'oregano', 'sage', 'parsley',
 'rosemary', 'tarragon', 'thyme', 'paprika', 'cumin']

In [47]:
%xmode Verbose
import re
#findinng the boolean indexing if the dataframe has these certain spices in the list or not 
spice_df = pd.DataFrame({
    spice : recipes.ingredients.str.contains(spice,re.IGNORECASE
                                             ) for spice in spice_list})

Exception reporting mode: Verbose

In [48]:
spice_df

,salt,pepper,oregano,sage,parsley,rosemary,tarragon,thyme,paprika,cumin
0,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,True,True,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
173273,False,False,False,False,False,False,False,False,False,False
173274,False,False,False,False,False,False,False,False,False,False
173275,True,True,False,False,False,False,False,False,True,True
173276,True,True,False,False,False,False,False,False,False,False
173277,True,False,False,False,False,False,False,False,False,False

In [49]:
#selecting ingredients with parslye parpika and sage

In [52]:
selection = spice_df.query('parsley&paprika&tarragon')

In [54]:
len(selection)

10

In [55]:
#so there are 10 dishes with with these three ingrdients

In [57]:
recipes.name[selection.index]

2069      All cremat with a Little Gem, dandelion and wa...
74964                         Lobster with Thermidor butter
93768      Burton's Southern Fried Chicken with White Gravy
113926                     Mijo's Slow Cooker Shredded Beef
137686                     Asparagus Soup with Poached Eggs
140530                                 Fried Oyster Po’boys
158475                Lamb shank tagine with herb tabbouleh
158486                 Southern fried chicken in buttermilk
163175            Fried Chicken Sliders with Pickles + Slaw
165243                        Bar Tartine Cauliflower Salad
Name: name, dtype: object

In [58]:
#so there are 10 dishes according to ingridents that we have we can multiple possibly with varies combinatinn thatis never ending