In [2]:
#data aggregation on multiple indices

In [3]:
import pandas as pd 
import numpy as np

In [4]:
#creating heirarchical index for the index and columns 
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],
                                  names= ['year','visit']
                                )
columns = pd.MultiIndex.from_product([['Bob','Suzy','Michael'],['HR','Temp']],
                                    names = ['Name','Type'])

#making a fake data 
data = np.round(np.random.randn(4,6),1)#here we are making an array of 4,6 size and rounding that to 1 digit
data[:,::2] *= 10
data += 37

#creating the data frame 
health_data = pd.DataFrame(data,index = index , columns = columns)

In [5]:
health_data

Name         Bob        Suzy       Michael
Type          HR  Temp    HR  Temp      HR  Temp
year visit
2013 1      33.0  38.0  31.0  36.8    27.0  37.8
     2      26.0  36.0  35.0  37.2    39.0  36.3
2014 1      45.0  38.7  37.0  38.7    45.0  38.3
     2      58.0  34.9  49.0  38.3    35.0  36.2

In [9]:
#concating and appending the data sets

In [11]:
import pandas as pd 
import numpy as np

In [16]:
#function for making concated data frames 
def make_df(cols,ind):
    "Makes a quick Data frames"
    data = {c:[str(c)+str(1) for i in ind] for c in cols}
    return pd.DataFrame(data,ind)

In [17]:
make_df('ABC',range(3))

    A   B   C
0  A1  B1  C1
1  A1  B1  C1
2  A1  B1  C1

In [19]:
#making a class that will allow use to use multiple data frames side by side 
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}{1}
    """
    def __init__(self,*args):#storing all the arguments means variable etc 
        self.args = args

    def _repr_html_(self):
        return '\n'.join(self.template.format(a,eval(a)._repr_html_()) for a in self.args)

    def _repr_(self):
        return '\n\n'.join(a+'\n'+repr(eval(a)) for a in self.args)