# Vectorized operation in Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
#vectorization 
x = np.array([2,3,3,4,5,5,6,6])
x*2

array([ 4,  6,  6,  8, 10, 10, 12, 12])

In [3]:
#problem with  vectorizatoin it is very verbose means details about thing 
data = ['paul','maRy','Pink','Blue']
[s.capitalize() for s in data]

['Paul', 'Mary', 'Pink', 'Blue']

In [4]:
#by pandas it is very conveniencet and error prone free 
data = pd.Series(['paul','chinki','kai','tyson'])
data.str.capitalize()

0      Paul
1    Chinki
2       Kai
3     Tyson
dtype: object

In [5]:
#lets start today work 
#table of the pandas string method 
monte = pd.Series(['Graham Chapman', 'John Cleese', 'Terry Gilliam',
'Eric Idle', 'Terry Jones', 'Michael Palin'])

In [6]:
monte

0    Graham Chapman
1       John Cleese
2     Terry Gilliam
3         Eric Idle
4       Terry Jones
5     Michael Palin
dtype: object

In [7]:
#mthods of the pandas for doing the vectorization with the pandas 
monte.str.len()

0    14
1    11
2    13
3     9
4    11
5    13
dtype: int64

In [8]:
monte.str.lower()

0    graham chapman
1       john cleese
2     terry gilliam
3         eric idle
4       terry jones
5     michael palin
dtype: object

In [9]:
monte.str.capitalize()

0    Graham chapman
1       John cleese
2     Terry gilliam
3         Eric idle
4       Terry jones
5     Michael palin
dtype: object

In [10]:
monte.str.upper()#for captilzing every letter in the sentence

0    GRAHAM CHAPMAN
1       JOHN CLEESE
2     TERRY GILLIAM
3         ERIC IDLE
4       TERRY JONES
5     MICHAEL PALIN
dtype: object

monte.str.isdigit()

In [11]:
monte.str.isdigit()#for checking series have digit  or not

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [12]:
monte.str.split()#for splitting the different words in the seiries

0    [Graham, Chapman]
1       [John, Cleese]
2     [Terry, Gilliam]
3         [Eric, Idle]
4       [Terry, Jones]
5     [Michael, Palin]
dtype: object

In [13]:
monte.str.startswith('T')#for cheking if the values starts with desired character or not

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [14]:
monte.str.startswith('A')

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [15]:
#methods using the regular expresions

In [16]:
monte.str.extract('([A-Za-z]+)',expand=False)

0     Graham
1       John
2      Terry
3       Eric
4      Terry
5    Michael
dtype: object

In [17]:
monte.str.extract('([A-Za-z]+)',expand = False)

0     Graham
1       John
2      Terry
3       Eric
4      Terry
5    Michael
dtype: object

In [18]:
monte.str.findall(r'^[^AEIOU].*[^aeiou]$')#so here basically we are saying that find the values which are not starting and ending with the vowel so we will just get the words that are starting with the consonants

0    [Graham Chapman]
1                  []
2     [Terry Gilliam]
3                  []
4       [Terry Jones]
5     [Michael Palin]
dtype: object

In [19]:
#Miscellenous methods in between the pandas and pythonn strings

Other methods then basic pandas vectorization methods and regular expression methods 
get Indexes each element
slice Slices each element
slice_replace Replaces slice in each element with the passed value
cat Concatenates strings
repeat Repeats values
normalize Returns Unicode form of strings
pad Adds whitespace to left, right, or both sides of strings
wrap Splits long strings into lines with length less than a given width
join Joins strings in each element of the Series with the passed separator
get_dummies Extracts dummy variables as a DataFrame

In [20]:
#normal indexing 
monte[0:3]

0    Graham Chapman
1       John Cleese
2     Terry Gilliam
dtype: object

In [21]:
#slicing of the str 
monte.str[0:3]

0    Gra
1    Joh
2    Ter
3    Eri
4    Ter
5    Mic
dtype: object

In [24]:
#splliting through the indexes using the slicing of the string 
monte.str.split().str[-1]

0    Chapman
1     Cleese
2    Gilliam
3       Idle
4      Jones
5      Palin
dtype: object

In [25]:
#indicator codes - codes such we specify something inn the data to make the data look clean and stable
#for example all the people with failing marks as F and students in these certain range or duplicats as a, b c etc

In [26]:
# #vectorizing the indicator codes 
# as A = “born in America,” B = “born in the United Kingdom,” C = “likes cheese,”
# D = “likes spam”:
full_monte = pd.DataFrame({'name':monte,
                          'info':['B|C|D','B|D','C|A','A|D','A|C|D','B|C']})

In [27]:
full_monte

             name   info
0  Graham Chapman  B|C|D
1     John Cleese    B|D
2   Terry Gilliam    C|A
3       Eric Idle    A|D
4     Terry Jones  A|C|D
5   Michael Palin    B|C

In [30]:
#getting dummies of the data 
full_monte['info'].str.get_dummies('|')

   A  B  C  D
0  0  1  1  1
1  0  1  0  1
2  1  0  1  0
3  1  0  0  1
4  1  0  1  1
5  0  1  1  0

In [31]:
#mini vector  project

Example - Recipe database

In [33]:
import pandas as pd 
import numpy as np

In [35]:
recipes = pd.read_csv('recipes.csv')

In [36]:
recipes

,Unnamed: 0,recipe_name,prep_time,cook_time,total_time,servings,yield,ingredients,directions,rating,url,cuisine_path,nutrition,timing,img_src
0,0,Apple-Cranberry Crostada,NaN,NaN,NaN,8,6 to 8 - servings,"3 tablespoons butter, 2 pounds Granny Smith ap...",Heat butter in a large skillet over medium-hig...,4.4,https://www.allrecipes.com/recipe/76931/apple-...,/Desserts/Fruit Desserts/Apple Dessert Recipes/,"Total Fat 18g 23%, Saturated Fat 7g 34%, Chole...","Servings: 8, Yield: 6 to 8 - servings",https://www.allrecipes.com/thmb/Tf1wH73bfH6Oql...
1,1,Apple Pie by Grandma Ople,30 mins,1 hrs,1 hrs 30 mins,8,1 9-inch pie,"8 small Granny Smith apples, or as needed, ½ c...","Peel and core apples, then thinly slice. Set a...",4.8,https://www.allrecipes.com/recipe/12682/apple-...,/Desserts/Pies/Apple Pie Recipes/,"Total Fat 19g 24%, Saturated Fat 9g 46%, Chole...","Prep Time: 30 mins, Cook Time: 1 hrs, Total Ti...",https://www.allrecipes.com/thmb/1I95oiTGz6aEpu...
2,2,Sarah's Homemade Applesauce,10 mins,15 mins,25 mins,4,NaN,"4 apples - peeled, cored and chopped, ¾ cup w...","Combine apples, water, sugar, and cinnamon in ...",4.8,https://www.allrecipes.com/recipe/51301/sarahs...,/Side Dish/Applesauce Recipes/,"Total Fat 0g 0%, Sodium 3mg 0%, Total Carbohyd...","Prep Time: 10 mins, Cook Time: 15 mins, Total ...",https://www.allrecipes.com/thmb/VY5d0tZHB8xz6y...
3,3,Apple Crisp,30 mins,45 mins,1 hrs 15 mins,12,1 9x13-inch pan,"10 cups all-purpose apples, peeled, cored and ...",Preheat the oven to 350 degrees F (175 degrees...,4.7,https://www.allrecipes.com/recipe/12409/apple-...,/Desserts/Crisps and Crumbles Recipes/Apple Cr...,"Total Fat 8g 11%, Saturated Fat 5g 25%, Choles...","Prep Time: 30 mins, Cook Time: 45 mins, Total ...",https://www.allrecipes.com/thmb/uAzhPOh86PfR-N...
4,4,Apple Pie Filling,20 mins,20 mins,2 hrs 40 mins,40,5 9-inch pies,"18 cups thinly sliced apples, 3 tablespoons le...",Toss apples with lemon juice in a large bowl a...,4.7,https://www.allrecipes.com/recipe/12681/apple-...,/Desserts/Pies/Apple Pie Recipes/,"Total Fat 0g 0%, Sodium 61mg 3%, Total Carbohy...","Prep Time: 20 mins, Cook Time: 20 mins, Additi...",https://www.allrecipes.com/thmb/c0bbYaS1V_mTt_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1085,1085,Date-Nut Balls,15 mins,10 mins,30 mins,48,4 dozen balls,"14 tablespoons butter, 1 cup pitted chopped da...",Melt butter in a saucepan over medium heat; co...,3.8,https://www.allrecipes.com/recipe/240653/date-...,/Desserts/Cookies/Fruit Cookie Recipes/Date/,"Total Fat 5g 6%, Saturated Fat 2g 12%, Cholest...","Prep Time: 15 mins, Cook Time: 10 mins, Additi...",https://www.allrecipes.com/thmb/LXm_15zLymhZ7c...
1086,1086,Jamaica Cake,NaN,NaN,NaN,14,1 - 13x9 inch pan,"2 cups white sugar, 1 ½ cups vegetable oil, 1 ...","Mix together sugar, vegetable oil, pecans, flo...",4.6,https://www.allrecipes.com/recipe/7509/jamaica...,/Desserts/Fruit Desserts/Banana Dessert Recipes/,"Total Fat 33g 43%, Saturated Fat 4g 21%, Chole...","Servings: 14, Yield: 1 - 13x9 inch pan",https://www.allrecipes.com/thmb/tI7g5xY5-qPV5v...
1087,1087,Best Hot Sauce,10 mins,20 mins,30 mins,100,2 cups,"10 fresh hot chile peppers, stems removed, 1 ...","Place peppers, onion, dates, basil, parsley, t...",4.9,https://www.allrecipes.com/recipe/242153/best-...,/Side Dish/Sauces and Condiments/,"Total Fat 1g 1%, Saturated Fat 0g 1%, Sodium 2...","Prep Time: 10 mins, Cook Time: 20 mins, Total ...",https://www.allrecipes.com/thmb/80wUYzFvbycfxx...
1088,1088,Moist Date Nut Bread,15 mins,50 mins,1 hrs 35 mins,12,1 9x5-inch loaf,"2 ½ cups chopped dates, ¼ cup butter, 1 cup bo...",Preheat the oven to 350 degrees F (175 degrees...,4.5,https://www.allrecipes.com/recipe/51446/moist-...,/Breakfast and Brunch/Breakfast Bread Recipes/,"Total Fat 10g 13%, Saturated Fat 3g 16%, Chole...","Prep Time: 15 mins, Cook Time: 50 mins, Additi...",https://www.allrecipes.com/thmb/bYsnompJZ6UAF9...
1089,1089,Chef John's Chocolate Energy Bars,15 mins,NaN,3 hrs,12,12 bars,"2 cups pitted Medjool dates, roughly chopped, ...","Place cashews, almonds, coconut, dates, cocoa,...",4.8,https://www.allrecipes.com/recipe/254452/chef-...,/Appetizers and Snacks/Snacks/Granola Bar Reci...,"Total Fat 22g 28%, Saturated Fat 7g 36%, Sodiu...","Prep Time: 15 mins, Additional Time: 2 hrs 45 ...",https://www.allrecipes.com/thmb/IOoj42MMo8YNKW...

In [38]:
recipes.iloc[0]

Unnamed: 0                                                      0
recipe_name                              Apple-Cranberry Crostada
prep_time                                                     NaN
cook_time                                                     NaN
total_time                                                    NaN
servings                                                        8
yield                                           6 to 8 - servings
ingredients     3 tablespoons butter, 2 pounds Granny Smith ap...
directions      Heat butter in a large skillet over medium-hig...
rating                                                        4.4
url             https://www.allrecipes.com/recipe/76931/apple-...
cuisine_path      /Desserts/Fruit Desserts/Apple Dessert Recipes/
nutrition       Total Fat 18g 23%, Saturated Fat 7g 34%, Chole...
timing                      Servings: 8, Yield: 6 to 8 - servings
img_src         https://www.allrecipes.com/thmb/Tf1wH73bfH6Oql...
Name: 0, dtype: object

In [41]:
#so my work is to make a list of the ingrdient of making a recipe 
recipes.ingredients.str.len().describe()#so here we are taking description of the recipes ingrdients lenght of the full data

count    1090.000000
mean      226.859633
std       101.681860
min        10.000000
25%       156.000000
50%       210.000000
75%       287.750000
max       625.000000
Name: ingredients, dtype: float64

In [42]:
#so max chracters are 625 and average chracters is 226 and no of ingrdients of the recipes in the data is 1090

In [46]:
#let find which recipe have 625 character of ingridient 
recipes.recipe_name[np.argmax(recipes.ingredients.str.len().describe())]

'Apple-Cranberry Crostada'

In [47]:
#so the recipe with the highest number of ingredients is apple cranberry  crostada

In [50]:
#letss find the withe lowest character 
recipes.recipe_name[np.argmin(recipes.ingredients.str.len().describe())]

'Apple Crisp'

In [51]:
#apple crisp is with lowest